const easy = {
    'head': '/emojis/easy/hooo.png',
    ':hooo': '/emojis/easy/hooo.png',
    ':hugging': '/emojis/easy/hugging.png',
    ':huntman': '/emojis/easy/huntman.png',
    ':idea': '/emojis/easy/idea.png',
    ':idontcare': '/emojis/easy/idontcare.png',
}

const modern = {
    'head': '/emojis/modern/idontcare.png',
    ':hooo': '/emojis/modern/hooo.png',
    ':hugging': '/emojis/modern/hugging.png',
    ':huntman': '/emojis/modern/huntman.png',
    ':idea': '/emojis/modern/idea.png',
    ':idontcare': '/emojis/modern/idontcare.png',
    ':hooo1': '/emojis/modern/hooo.png',
    ':hugging2': '/emojis/modern/hugging.png',
    ':huntman3': '/emojis/modern/huntman.png',
    ':idea4': '/emojis/modern/idea.png',
    ':idontcare5': '/emojis/modern/idontcare.png',
    ':hooo6': '/emojis/modern/hooo.png',
    ':hugging7': '/emojis/modern/hugging.png',
    ':huntman8': '/emojis/modern/huntman.png',
    ':idea9': '/emojis/modern/idea.png',
    ':idontcare0': '/emojis/modern/idontcare.png',
    ':idontcare1': '/emojis/modern/idontcare.png',
    ':idontcare2': '/emojis/modern/idontcare.png',
    ':idontcare3': '/emojis/modern/idontcare.png',
    ':idontcare4': '/emojis/modern/idontcare.png',
    ':idontcarel': '/emojis/modern/idontcare.png',
    ':idontcare6': '/emojis/modern/idontcare.png',
    ':idontcare9': '/emojis/modern/idontcare.png',
    ':idontcare8': '/emojis/modern/idontcare.png',
    ':idontcare7': '/emojis/modern/idontcare.png',
    ':idontcare11': '/emojis/modern/idontcare.png',
    ':idontcare21': '/emojis/modern/idontcare.png',
    ':idontcare31': '/emojis/modern/idontcare.png',
    ':idontcare41': '/emojis/modern/idontcare.png',
    ':idontcare51': '/emojis/modern/idontcare.png',
    ':idontcare61': '/emojis/modern/idontcare.png',
    ':idontcare71': '/emojis/modern/idontcare.png',
    ':idontcare81': '/emojis/modern/idontcare.png',
    ':idontcare12': '/emojis/modern/idontcare.png',
    ':idontcare22': '/emojis/modern/idontcare.png',
    ':idontcare32': '/emojis/modern/idontcare.png',
    ':idontcare42': '/emojis/modern/idontcare.png',
    ':idontcare52': '/emojis/modern/idontcare.png',
    ':idontcare62': '/emojis/modern/idontcare.png',
    ':idontcare72': '/emojis/modern/idontcare.png',
    ':idontcare82': '/emojis/modern/idontcare.png',
}


export const emojis = [easy, modern, easy, modern]